# Important Notes:
# Every field you add must be added to build-logic/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.0.1
group=io.github.maxomatic458.conduit
java_version=25

# Common
minecraft_version=26.2
mod_name=Conduit
mod_author=maxomatic458
mod_id=conduit
license=MIT
credits=
description=Host and join Minecraft servers without port forwarding, by tunnelling the game over the iroh peer-to-peer network. Share a connect ID instead of an IP.
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3
cloth_config_version=26.2.155

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

## The official n0 UniFFI kotlin bindings
iroh_version=1.1.0
kotlin_version=2.2.21
coroutines_version=1.9.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
